#version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      # envirnonments can be used in either form
      # either as an array syntex or as a mapping system
      # lets use a mapping system
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      # lets do this in array mapping form
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
